use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/categories",
        "community",
        "categories.list",
    )
    .with_required_permission("community.categories.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/categories",
        "community",
        "categories.create",
    )
    .with_required_permission("community.categories.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/categories/{categoryId}",
        "community",
        "categories.retrieve",
    )
    .with_required_permission("community.categories.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/community/categories/{categoryId}",
        "community",
        "categories.update",
    )
    .with_required_permission("community.categories.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/community/categories/{categoryId}",
        "community",
        "categories.delete",
    )
    .with_required_permission("community.categories.write"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/categories/{categoryId}/join",
        "community",
        "categories.join",
    )
    .with_required_permission("community.members.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/categories/{categoryId}/members",
        "community",
        "members.list",
    )
    .with_required_permission("community.members.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/categories/{categoryId}/members/current",
        "community",
        "members.retrieve",
    )
    .with_required_permission("community.members.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/community/categories/{categoryId}/members/{memberId}",
        "community",
        "members.update",
    )
    .with_required_permission("community.members.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/community/categories/{categoryId}/members/{memberId}",
        "community",
        "members.delete",
    )
    .with_required_permission("community.members.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/categories/{categoryId}/groups",
        "community",
        "groups.list",
    )
    .with_required_permission("community.groups.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/categories/{categoryId}/groups",
        "community",
        "groups.create",
    )
    .with_required_permission("community.groups.write"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/community/categories/{categoryId}/groups/{groupId}",
        "community",
        "groups.update",
    )
    .with_required_permission("community.groups.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/community/categories/{categoryId}/groups/{groupId}",
        "community",
        "groups.delete",
    )
    .with_required_permission("community.groups.write"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/categories/{categoryId}/members/activate",
        "community",
        "members.activate",
    )
    .with_required_permission("community.memberships.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/categories/{categoryId}/tiers",
        "community",
        "tiers.list",
    )
    .with_required_permission("community.tiers.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/categories/{categoryId}/tiers",
        "community",
        "tiers.create",
    )
    .with_required_permission("community.tiers.write"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/community/categories/{categoryId}/tiers/{tierId}",
        "community",
        "tiers.update",
    )
    .with_required_permission("community.tiers.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/community/categories/{categoryId}/tiers/{tierId}",
        "community",
        "tiers.delete",
    )
    .with_required_permission("community.tiers.write"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/categories/{categoryId}/tiers/{tierId}/publish",
        "community",
        "tiers.publish",
    )
    .with_required_permission("community.tiers.write"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/categories/{categoryId}/tiers/{tierId}/unpublish",
        "community",
        "tiers.unpublish",
    )
    .with_required_permission("community.tiers.write"),
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/community/feed",
        "community",
        "feed.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/entries",
        "community",
        "entries.create",
    )
    .with_required_permission("community.entries.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/entries/{entryId}",
        "community",
        "entries.retrieve",
    )
    .with_required_permission("community.entries.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/community/entries/{entryId}",
        "community",
        "entries.update",
    )
    .with_required_permission("community.entries.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/community/entries/{entryId}",
        "community",
        "entries.delete",
    )
    .with_required_permission("community.entries.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/entries/{entryId}/recommendations",
        "community",
        "entries.recommendations.list",
    )
    .with_required_permission("community.recommendations.read"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/entries/{entryId}/publication_readiness",
        "community",
        "entries.publicationReadiness.retrieve",
    )
    .with_required_permission("community.entries.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/entries/{entryId}/reactions",
        "community",
        "reactions.create",
    )
    .with_required_permission("community.reactions.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/community/entries/{entryId}/comments",
        "community",
        "comments.list",
    )
    .with_required_permission("community.comments.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/community/entries/{entryId}/comments",
        "community",
        "comments.create",
    )
    .with_required_permission("community.comments.write"),
];

pub fn gateway_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(ROUTES)
}

#[cfg(test)]
mod tests {
    use sdkwork_web_core::RouteAuth;

    use super::gateway_route_manifest;

    #[test]
    fn feed_list_is_public() {
        let manifest = gateway_route_manifest();
        let route = manifest
            .match_route("GET", "/app/v3/api/community/feed")
            .expect("community feed must be registered");
        assert_eq!(RouteAuth::Public, route.auth);
        assert_eq!("feed.list", route.operation_id);
    }
}
