name: sdkwork_community_flutter_mobile
description: SDKWork Community Flutter Mobile Application
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sdkwork_community_flutter_mobile_core:
    path: packages/sdkwork_community_flutter_mobile_core
  sdkwork_community_flutter_mobile_community:
    path: packages/sdkwork_community_flutter_mobile_community

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
