use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/community/categories",
        "community",
        "categories.management.list",
    )
    .with_required_permission("community.categories.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/community/categories",
        "community",
        "categories.create",
    )
    .with_required_permission("community.categories.manage"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/community/categories/{categoryId}",
        "community",
        "categories.update",
    )
    .with_required_permission("community.categories.manage"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/community/categories/{categoryId}",
        "community",
        "categories.delete",
    )
    .with_required_permission("community.categories.manage"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/community/entries",
        "community",
        "entries.management.list",
    )
    .with_required_permission("community.moderation.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/community/entries/{entryId}/moderation",
        "community",
        "entries.moderation.create",
    )
    .with_required_permission("community.moderation.manage"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/community/entries/{entryId}/feature",
        "community",
        "entries.feature",
    )
    .with_required_permission("community.moderation.manage"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/community/entries/{entryId}/pin",
        "community",
        "entries.pin",
    )
    .with_required_permission("community.moderation.manage"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/community/entries/{entryId}",
        "community",
        "entries.delete",
    )
    .with_required_permission("community.moderation.manage"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/community/moderation/queue",
        "community",
        "moderation.queue.list",
    )
    .with_required_permission("community.moderation.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/community/recommendations/rebuild",
        "community",
        "recommendations.rebuild",
    )
    .with_required_permission("community.recommendations.manage"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/community/circles/{categoryId}",
        "community",
        "circles.update",
    )
    .with_required_permission("community.categories.manage"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/community/members",
        "community",
        "members.management.list",
    )
    .with_required_permission("community.members.read"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/community/members/{memberId}",
        "community",
        "members.update",
    )
    .with_required_permission("community.members.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/community/members/{memberId}",
        "community",
        "members.delete",
    )
    .with_required_permission("community.members.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/community/groups",
        "community",
        "groups.management.list",
    )
    .with_required_permission("community.groups.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/community/groups",
        "community",
        "groups.create",
    )
    .with_required_permission("community.groups.write"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/community/groups/{groupId}",
        "community",
        "groups.update",
    )
    .with_required_permission("community.groups.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/community/groups/{groupId}",
        "community",
        "groups.delete",
    )
    .with_required_permission("community.groups.write"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/backend/v3/api/community/tiers",
        "community",
        "tiers.management.list",
    )
    .with_required_permission("community.tiers.read"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/community/tiers",
        "community",
        "tiers.create",
    )
    .with_required_permission("community.tiers.write"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/backend/v3/api/community/tiers/{tierId}",
        "community",
        "tiers.update",
    )
    .with_required_permission("community.tiers.write"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/backend/v3/api/community/tiers/{tierId}",
        "community",
        "tiers.delete",
    )
    .with_required_permission("community.tiers.write"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/community/tiers/{tierId}/publish",
        "community",
        "tiers.publish",
    )
    .with_required_permission("community.tiers.write"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/backend/v3/api/community/tiers/{tierId}/unpublish",
        "community",
        "tiers.unpublish",
    )
    .with_required_permission("community.tiers.write"),
];

pub fn gateway_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(ROUTES)
}
